### ISSUE TITLE
docsify main page is blank

### ISSUE THREAD

**Issue by keturn** [Terasology/TutorialProfiling#4]
https://terasology.github.io/TutorialProfiling/ says 404 in the main body and has a blank sidebar.

It should have a link to https://terasology.github.io/TutorialProfiling/#/Monitoring%20Metrics%20with%20JMC%20-%20JDK%20Mission%20Control.md

**Comment by jdrueckert** [comment]
Thanks for reporting this :+1: 
#5 should fix the issue :slightly_smiling_face:
